# @package _group_
_target_: src.components.data.default_data_component.DefaultDataComponent

dataset_name: "gsm8k"
dataset_path: "openai/gsm8k"
dataset_config_name: "main"
max_train_samples: null # None = load it all
max_eval_samples: null # None = load it all
gsm8k_config: {}
finqa_config: {} 