defaults:
  - data_component@data: default
  - model_component@model: default
  - reward_component@reward: default
  - training_loop_component@train: default
  - evaluation_component@eval: default
  - prompts@prompts: math_reasoning # Add prompts to defaults, pointing to the 'default.yaml' in the 'prompts' group
  - _self_ # Allows overriding defaults and parameters from CLI
  # For observers, we define a list directly in this config.
  # Each item in the list must have a _target_ key for instantiation.

# Top-level pipeline parameters
logging_level: INFO
log_dir: outputs

# Observers configuration
# Each item in the list needs a _target_ for Hydra's instantiation.
# The WandbObserver specifically expects its parameters under a 'config' key.
observers:
  - _target_: src.components.observers.wandb_observer.WandbObserver
    config: # This 'config' key is specific to how WandbObserver is structured
      wandb_project: "grpo_refactor_test_hydra"
      wandb_entity: null # Specify your W&B entity if not using default
      wandb_run_name: "grpo_${now:%Y%m%d_%H%M%S}"
      log_config_to_wandb: True

inference:
  run: false
  query: "What is the sqrt of 101?" 