reward_functions:
  - category: "answer_matching"
    type: "gsm8k_answer_check"
    params:
      correct_reward: 3.0
      stripped_match_reward: 1.5
      numerical_close_reward_strong: 0.5
      numerical_close_reward_weak: 0.25
      wrong_penalty: -1.0
      unparseable_penalty: -1.0
  
  - category: "format_checking"
    type: "match_format_approximately"
    params:
      per_marker_reward: 0.5
      per_marker_penalty: -0.5
  
  - category: "format_checking"
    type: "match_format_exactly"
    params:
      reward_value: 3.0

  - category: "answer_matching"
    type: "check_numbers"
    params:
      no_match_score: 0.0
      match_score: 1.5
      conversion_error_score: 0.0