# @package _group_
_target_: src.components.evaluation.default_evaluation_component.DefaultEvaluationComponent

# Parameters for DefaultEvaluationComponent
enabled: True # This can be used to conditionally instantiate or run the component
eval_datasets_names: ["gsm8k"]
eval_steps: 50
eval_max_new_tokens: 1024
eval_num_samples: null # setting to null means all of it
eval_batch_size: 256